version: '3.3'

services:

  standalone:
    image: apachepulsar/pulsar:2.8.0
    container_name: standalone
    ports:
      - 8080
      - 6650
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone"      
    networks:
      local-pulsar-net:
      
  dashboard:
    image: apachepulsar/pulsar-dashboard
    container_name: dashboard
    depends_on:
      - standalone
    ports:
      - "9090:80"
    environment:
      - SERVICE_URL=http://standalone:8080
    networks:
      local-pulsar-net:
          
  cassandra:
    image: cassandra:latest
    container_name: cassandra   
    ports:
    - 7000:7000
    - 7001:7001
    - 7199:7199
    - 9042:9042
    - 9160:9160
    volumes:
      - ~/volumes/cass4:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
      #- ~/volumes/etc/cass1:/etc/cassandra   # Use your own config files for full control
    networks:
      local-pulsar-net:
          
  cassandra-web:
    image: markusgulden/cassandra-web
    container_name: cassandra-web
    depends_on:
    - cassandra
    environment:
      #CASSANDRA_HOST_IPS: 10.20.0.168
      #192.168.80.2
      #from docker inspect
      CASSANDRA_HOST_IPS: 192.168.96.1
     # CASSANDRA_HOST_IPS: 192.168.0.1
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
    - 3000:3000
    networks:
      local-pulsar-net:
  
  pulsar:
    image: pulsar
    build: ./pulsar
    container_name: pulsar
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - standalone
      - cassandra
    depends_on: 
      - standalone
      - cassandra
    ports:
      - '3021:3021'  
    networks:
      - local-pulsar-net      
   
  magnetar:
    image: magnetar
    build: ./magnetar
    container_name: magnetar   
    links:
      - standalone
      - cassandra
    depends_on: 
      - standalone
      - cassandra
    ports:
      - '4021:4021'  
    networks:
      - local-pulsar-net
      
  shine:
    image: shine
    build: ./shine
    container_name: shine   
    links:
      - standalone
      - cassandra
    depends_on: 
      - standalone
      - cassandra
    ports:
      - '5021:5021'  
    networks:
      - local-pulsar-net

networks:
  local-pulsar-net: